version: "3.8"

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/server/app
    environment:
      - DATABASE_URL=postgresql://dibkb:password@db:5432/interface-etl
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dibkb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=interface-etl
    ports:
      - 5432:5432

volumes:
  postgres_data:
