name: CD

on:
  push:
    branches:
      - prod # Trigger on pushes to the prod branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dibkb/interface-assignment-server:latest

      - name: Verify Pushed Image
        run: docker pull dibkb/interface-assignment-server:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Ensure Docker Compose is installed and up to date
            sudo curl -L "https://github.com/docker/compose/releases/download/$(sudo curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Pull the latest image from Docker Hub
            sudo docker pull dibkb/interface-assignment-server:latest

            # Stop and remove the old container if it exists
            sudo docker stop interface-assignment-server || true
            sudo docker rm interface-assignment-server || true

            docker-compose -f docker-compose.yml up -d

            # Clean up unused volumes
            sudo docker system prune -f --volumes
